<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <IsPackable>True</IsPackable>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <Description>Converts a PaintCode document into Svg drawings and an svgc project.</Description>
    <PackageId>Svg.PaintCode</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>svg;paintcode;expressions;import;authoring;graphics</PackageTags>
  </PropertyGroup>

  <Import Project="..\..\build\SourceLink.props" />
  <Import Project="..\..\build\SignAssembly.props" />
  <Import Project="..\..\build\ReferenceAssemblies.props" />

  <ItemGroup>
    <ProjectReference Include="..\Svg.Expressions\Svg.Expressions.csproj" />
    <ProjectReference Include="..\Svg.CodeGen.Skia.Projects\Svg.CodeGen.Skia.Projects.csproj" />
  </ItemGroup>

</Project>
