// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ShimSkiaSharp;
using Svg.CodeGen.Skia.Expressions;

namespace Svg.CodeGen.Skia;

public static class SkiaCSharpCodeGen
{
    public static string Generate(SKPicture picture, string namespaceName, string className)
        => Generate(picture, namespaceName, className, SvgCodeDeclarations.Empty);

    public static string Generate(SKPicture picture, string namespaceName, string className, SvgCodeDeclarations? declarations)
    {
        declarations ??= SvgCodeDeclarations.Empty;

        var (compiler, lets) = declarations.Resolve();

        var counter = new SkiaCSharpCodeGenCounter();
        var indent = "            ";

        // Record the body first: which helper methods the class needs is decided by what the
        // expression compiler actually produced.
        var bodyBuilder = new StringBuilder();
        var counterPicture = ++counter.Picture;

        using (SymCSharpEmitter.UseCompiler(compiler))
        {
            picture.ToSKPicture(counter, bodyBuilder, indent);
        }

        bodyBuilder.AppendLine($"{indent}return {counter.PictureVarName}{counterPicture};");
        var body = bodyBuilder.ToString();

        var parameters = declarations.Parameters;
        var isParameterized = parameters.Count > 0;
        var parameterList = BuildParameterList(parameters, declarations);
        var argumentList = string.Join(", ", parameters.Select(p => p.Name));

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine($"");
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine($"{{");
        sb.AppendLine($"    using System;");
        sb.AppendLine($"    using SkiaSharp;");
        sb.AppendLine($"");
        sb.AppendLine($"    public static class {className}");
        sb.AppendLine($"    {{");

        // A picture built from parameters cannot be cached in a static field, so the
        // parameterless shape is kept exactly as it was for documents without declarations.
        if (!isParameterized)
        {
            sb.AppendLine($"        public static SKPicture Picture {{ get; }}");
            sb.AppendLine($"");
            sb.AppendLine($"        static {className}()");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            Picture = Record();");
            sb.AppendLine($"        }}");
            sb.AppendLine($"");
        }

        sb.AppendLine($"        {(isParameterized ? "public" : "private")} static SKPicture Record({parameterList})");
        sb.AppendLine($"        {{");

        foreach (var (name, type, code) in lets)
        {
            sb.AppendLine($"{indent}{ExprCompiler.CSharpTypeOf(type)} {name} = {code};");
        }

        if (lets.Count > 0)
        {
            sb.AppendLine($"");
        }

        sb.Append(body);

        sb.AppendLine($"        }}");
        sb.AppendLine($"");

        if (isParameterized)
        {
            // The picture is built for this one call and cannot escape, so Draw owns it.
            // Disposing releases the native memory at a known point instead of leaving it to a
            // finalizer. Record keeps its own contract: what it returns, the caller owns.
            sb.AppendLine($"        public static void Draw(SKCanvas {counter.CanvasVarName}, {parameterList})");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            using (var {counter.PictureVarName} = Record({argumentList}))");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                {counter.CanvasVarName}.DrawPicture({counter.PictureVarName});");
            sb.AppendLine($"            }}");
            sb.AppendLine($"        }}");
        }
        else
        {
            sb.AppendLine($"        public static void Draw(SKCanvas {counter.CanvasVarName})");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            {counter.CanvasVarName}.DrawPicture(Picture);");
            sb.AppendLine($"        }}");
        }

        // Scan everything emitted so far, not just the picture body: helpers are just as likely
        // to be referenced from a let or a parameter default.
        foreach (var helper in RequiredHelpers(sb.ToString()))
        {
            sb.AppendLine($"");
            foreach (var line in helper)
            {
                sb.AppendLine(line.Length == 0 ? "" : $"        {line}");
            }
        }

        sb.AppendLine($"    }}");
        sb.AppendLine($"}}");

        return sb.ToString();
    }

    // A parameter is optional only when the author gave it a default. Inventing one for the rest
    // would make every argument skippable and put a value in the signature that appears nowhere
    // in the document.
    private static string BuildParameterList(
        IReadOnlyList<SvgCodeParameter> parameters,
        SvgCodeDeclarations declarations)
    {
        var rendered = new List<string>(parameters.Count);
        SvgCodeParameter? optional = null;

        foreach (var parameter in parameters)
        {
            var type = ExprCompiler.CSharpTypeOf(parameter.Type);
            var code = declarations.DefaultCodeFor(parameter);

            if (code is null)
            {
                // C# requires the optional ones last, and reordering the list silently would
                // change what every positional call site means.
                if (optional is { })
                {
                    throw new ExprException(
                        $"'{parameter.Name}' has no default but follows '{optional.Name}', which has one. In C# the parameters with defaults have to come last, so declare '{parameter.Name}' before it.",
                        0);
                }

                rendered.Add($"{type} {parameter.Name}");
                continue;
            }

            optional = parameter;
            rendered.Add($"{type} {parameter.Name} = {code}");
        }

        return string.Join(", ", rendered);
    }

    private static IEnumerable<string[]> RequiredHelpers(string body)
    {
        foreach (var helper in ExprHelpers.All)
        {
            if (body.IndexOf(helper.Key + "(", StringComparison.Ordinal) >= 0)
            {
                yield return helper.Value;
            }
        }
    }
}
